// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import { MobilettoOrmObject } from "mobiletto-orm-typedef";
export type VideoProfileDashType = MobilettoOrmObject & {
    manifestAssets: string[];
    hlsProfile: string;
    subProfiles: string;
};
